### ISSUE TITLE
Name, short description, client, link to project

### ISSUE THREAD

**Issue by leahbannon** [18F/dashboard#10]
Breaking out #1

**Comment by leahbannon** [comment]
Make sure the basic description clearly explains who the user is and why they benefit from this.

**Comment by gboone** [comment]
Would we be opposed to putting the projects.json file into the `_data` directory so we can use jekyll to pull that data instead of javascript? If you're not sure what I mean by that: http://jekyllrb.com/docs/datafiles/ explains how to add a dataset. Then every time we generate the site it will autoload the project data from the json file.

**Comment by RobertLRead** [comment]
Sounds like a good idea to me --- I have no Jekyll experience---I assume
you know better than I do how to do this.  Please think of yourself as the
lead engineer---I just put a little work into getting it ready for you.

On Wed, Sep 10, 2014 at 10:35 AM, Greg Boone notifications@github.com
wrote:

> Would we be opposed to putting the projects.json file into the _data
> directory so we can use jekyll to pull that data instead of javascript? If
> you're not sure what I mean by that: http://jekyllrb.com/docs/datafiles/
> explains how to add a dataset. Then every time we generate the site it will
> autoload the project data from the json file.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/dashboard/issues/10#issuecomment-55133928.

## 

Robert L. Read, PhD
Presidential Innovation Fellow, 2013

**Comment by leahbannon** [comment]
Yes, please do this! Thanks.

**Comment by gbinal** [comment]
+1
