### ISSUE TITLE
Add 18F Consulting

### ISSUE THREAD

**Issue by gbinal** [18F/dashboard#173]
It seems like 18F Consulting should be an item on 18f.gsa.gov/dashboard.  

cc @cscairns, @RobertLRead

**Comment by meiqimichelle** [comment]
18F Consulting is a branch of 18F like PIF, seems like. It doesn't seem like PIF should be on dashboard, so....hmmmm.....

I feel like this gets back to our questions of what metrics are best to show impact. They might be project-based, but they might not be. Or, some of them might be project based, but not all. The UX work on the 18F site is thinking about these questions, too, and should have thoughts to share with the group late this week or early next. Happy to discuss here as well :)

After all that, though: 18F Consulting is not a project, and so the structure of the dashboard in its current incarnation should not include it. However, we should think ahead on how best to track 18F Consulting projects/activities.

**Comment by gbinal** [comment]
Odd - I would expect the opposite.  Given the project's goal and audience, it would seem the opposite to me: the dashboard does a disservice by not better reflecting what we are working on and how we are doing it. I actually would say PIF makes sense on the dashboard and that both it and 18F Consulting are projects of ours.

**Comment by ultrasaurus** [comment]
Given that the dashboard shows software stages (alpha, beta, etc.) I assumed it was about software... or in other words, a dashboard for the 18F delivery team, not all of 18F (which includes external programs like PIF and other internal services like teamops)

Arguably, alpha and beta couple apply to programs, but I think that will make it more difficult to add detail to what the stages mean, which I was hoping would be added over time.

**Comment by meiqimichelle** [comment]
What I mean is this:
PIF and Consulting are not projects, they are branches:
![imag0333](https://cloud.githubusercontent.com/assets/4827522/5581554/3dba2c60-9019-11e4-9c77-969d0798926f.jpg)

The way Dashboard is structured now, it is tracking projects. It would not make sense to track Consulting and PIF as if they were projects -- we would need to track those branches at a project level as well.

But of course, the entire 18F site needs to be restructured so that the relationship between the bits of 18F is clear, and the way we track projects and progress will likely change as well.

So, +1 to @ultrasaurus : the dashboard is currently about tracking delivery team output.

**Comment by gbinal** [comment]
Okay.  FWIW, that seems like an unnecessary limitation to me driven by a semantic.  If the goal of /dashboard is `Provide transparency and insight into 18F work and values.`, I'd think we'd want to reflect what 18F is doing.  It'd seem that most of the aspects we're using to give insight into the the projects would be just as useful to express for Consulting and PIF.

**Comment by meiqimichelle** [comment]
Information architecture is not a semantic. Our site (18f.gsa.gov) is currently difficult to navigate and understand. Transparency != throwing all the information over a wall and hoping that it provides insight into what we're doing, as you know. We will provide info on Consulting and PIF, just not as part of the dashboard (as it is currently structured).

**Comment by gboone** [comment]
@gbinal I get that but agree with @ultrasaurus and @meiqimichelle here. I'm not sure how we sum up all the work 18F Consulting is doing into a monolithic project we could represent on the dashboard. It might seem semantic, but it's also disingenuous to create a project called 18F Consulting and list every GitHub repo 18FC has as if they're all serving the same goals and partner agencies, have the same impact, and are driving toward the production of working, potentially reusable pieces of software. That, to my understanding is not (always) what 18F Consulting is doing but it is what Dashboard is built to represent. That's why it's hard to imagine how an 18FC entry actually drives forward the bigger goal of giving transparency and insight to that work. On top of that, from what I understand of 18FC, there's a lot of work being done that isn't necessarily captured in GitHub. The repos generated for protosketching sessions, for example, only show a fragment of the work done by the 18F Consulting team that was on site. 

At a high level you're right: 18FC is part of who we are and we should find a way to be transparent about what we're doing. To that end, I'm open to the idea of representing individual 18FC<sup>1</sup> projects on the Dashboard if any of them resemble something closer to what the Dashboard is currently designed to handle. I'm also open to a future where Dashboard is less delivery team-centric. At the moment, however, it is better designed for longer-term projects that can be easily summarized by the code and in some cases design artifacts produced during development that have potential for reuse. For now, it cannot represent much else in a way that is meaningful, honest and accurate.

<hr/>
1. Every time I write that I think I'm writing about a soccer team

**Comment by gbinal** [comment]
Interesting.  In that case, would it help the dashboard and its goals to remove the /Developer Program?  By this logic, that would seem an enhancement to it, right?

**Comment by gboone** [comment]
I don't think so /Developer is a specific project targeted at a specific initiative, not unlike other projects represented on the dashboard. And the work can be reused and summarized by the code and design artifacts that constitute: http://18f.github.io/API-All-the-X/

**Comment by NoahKunin** [comment]
Closing due to correct application of `wontfix`. 18F Consulting is a business line, not a project. 18FC does not do their work in the open. 18FC work occasionally becomes 18F Delivery work, and would then be listed in the dashboard.
