### ISSUE TITLE
As an editor, I would like to be able to edit a separate yml file for my project

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#179]
having a single projects.yml file collides with our workflow since we all tend to update them at once when @jroo reminds us to

**Comment by ultrasaurus** [comment]
proposal:  when the projects.yml is read, also read all yaml files in a sibling projects/ directly and treat them if they were one giant yaml, then we don't have to change everything at once.

**Comment by mbland** [comment]
That's very easy to do, given the [hash-joiner gem](https://rubygems.org/gems/hash-joiner). Question is, what lives in the "projects.yml" file, and what lives in "projects/"? Also, the directory name might have to be different; don't know what Jekyll will do with a collision between NAME.yml and NAME/.

**Comment by ultrasaurus** [comment]
I suggested we leave projects.yaml just to ease migration.  Then whoever wants to (and new projects) could go in projects/ (or whatever we decide to call the directory).  But could change everything at once -- tho then we would want to wait till all the project data is updated this week and it kind of defeats my primary motivation :)

**Comment by mbland** [comment]
Just had a chat with @gboone about his idea for importing `project.yml` files from individual 18F GitHub repositories. It seems like we could set up a `hookshot` job to listen for Webhooks from individual repos that all hit the same endpoint, e.g. `/deploy-project-update`. We can parse the payload to see whether a repo just updated its `project.yml`, and pull down a copy using a command/URL like: `https://raw.githubusercontent.com/18F/dashboard/project.yml`.

The data from the `project.yml` file could then be joined in with any existing/remaining data from [data-private/projects.yml](https://github.com/18F/data-private/blob/master/projects.yml) and automatically committed, much like [the Hub's "submodules" `hookshot` endpoint](https://github.com/18F/hub/blob/master/deploy/fabfile.py) does currently.

In fact, if @gboone and other Dashboard folks prefer, we can make this a Hub feature request instead. Doesn't matter much to me, but #181 should go in first before it's added to the Dashboard.

**Comment by gboone** [comment]
> don't know what Jekyll will do with a collision between NAME.yml and NAME/

<strike>Worth looking into but I don't think it'll be a problem.<strike>

> I suggested we leave projects.yaml just to ease migration. Then whoever wants to (and new projects) could go in projects/ (or whatever we decide to call the directory).

We should definitely leave `projects.yaml` in place until we're ready to do a bigger migration.

I'm not really sure what to do with #180 right now. The goal, as I see it, is to make updating these projects easier and less prone to merge conflicts. If we're still pushing YAML files to `data-private` product leads will still potentially runs into problems with multiple people committing to the same repo and not being able to save or push changes because someone else did it before them. I think this will especially be a problem if people are using GitHub's editor to do it. It may make more sense to keep a file in GitHub repos (this is the idea @mbland is mentioning above) and let product leads manage it independently of what's going on in any other repo. I want to chat with more product leads about what makes more sense before we go and change things up.

**Comment by ultrasaurus** [comment]
@gboone if two people edit two different files and each does a pull request, my experience is that there is no merge conflict -- having separate project files creates this opportunity for Product Leads who want to use that approach

I agree that I good additional step would be to pull the files from the project repo, but that could be an incremental improvement after this one

**Comment by gboone** [comment]
@ultrasaurus Oh, totally. I meant if people are using GitHub's editor where they'll be unable to commit. (Example: I just tried to edit the team.yml file in `data-private` using the editor but couldn't save my changes because Michelle made two commits to the repo while I was editing.) In that case it's not merge conflicts, but definitely lost work.

**Comment by gboone** [comment]
Just chatted with @jroo about use of GitHub's editor for these files. I'm strongly in favor of at least discouraging it, not sure how an all out ban could really be enforced, but anyone editing these files will have a much more predictable experience pulling down the latest changes, committing any necessary changes, pulling again just in case someone else made changes, and then pushing. Something like this:

``` zsh
git pull
- edit files
git commit
git pull
git push
```

**Comment by ultrasaurus** [comment]
@gboone regarding lost work, that will rarely happen if each product lead only changes one whatever.yml file

**Comment by gboone** [comment]
As long as folks still follow a branch + pull request workflow, I suppose. I'll just have to get good at shaming anyone who commits directly to the staging branch.

**Comment by ultrasaurus** [comment]
@gboone I actually think it shoud work with a direct commit, but maybe worth testing

**Comment by ultrasaurus** [comment]
@gboone are there outstanding questions on this pull request?  It would make my life as a product lead way easier.

**Comment by gboone** [comment]
I understand how much easier this will make product lead's lives and apologize for this falling off my radar, all hands + 18f-site stuff took priority the last couple weeks.

There is at least one outstanding question in #180: will this create a situation where `_data/projects.yml` and a `_data/projects` both exist?

**Comment by gboone** [comment]
I think this was closed in 18F/data-private#190
