### ISSUE TITLE
Add analytics.usa.gov to dashboard 

### ISSUE THREAD

**Issue by gbinal** [18F/dashboard#211]

**Comment by gbinal** [comment]
Created yml file - https://github.com/18F/data-private/blob/master/projects/dap.yml

@mbland, @gboone, @yozlet, @wslack - who can get this to actually go live on /dashboard?

**Comment by mbland** [comment]
18F/hub#316 opens https://hub.18f.gov/hub/api/projects/ to public (i.e. unauthenticated) access. #212 updates the `_data/import-public.rb` script to use this endpoint (so that a public Hub release isn't required as a prerequisite) and adds DAP to the Dashboard.

BTW, with all of the Hub out in the open on the table, I'm looking to streamline this further. See 18F/hub#211 (Midas integration) for how we might be able to adapt the Dashboard to dynamically pull information from an endpoint. There's still a need to generate a page in `pages/project` for each project on the Dashboard, but this can possibly be changed to use API data+JS.
