### ISSUE TITLE
as a comms leader, I want to review and approve staged content

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#281]
We need a way for comms to review all the new content in the dashboard and then push it live when it is good.

This implies that staging would use the live team API, but production might use some kind of static data copied from staging.

**Comment by gboone** [comment]
Steps:
- [x] Disable automatic team-api updates to production
- [x] Begin version controlling a copy of `projects.json` in [the `_data/` directory](https://github.com/18F/dashboard/tree/staging/_data)
- [x] Leave all Dashboard webhooks in place. Dashboard will update staging with new team-api data automatically, deploying to production will require review and a pull request to `production` in order to deploy over.

**Comment by gboone** [comment]
This is done. The projects.json wasn't version controlled because we found a better way to get fresh data on production. That better way is refreshing the data during deployment. Changes to the go script in #282 make that happen. Now, if we need to do a production deploy of _just the data_ we do it by triggering a production deployment. We can do that by redelivering one of the webhooks in this repo's settings.
