### ISSUE TITLE
what do alpha and beta mean to people?

### ISSUE THREAD

**Issue by ultrasaurus** [18F/dashboard#287]
This is a multistep story
- [x] talk to product owners, what do they mean when they label their project "alpha" or "beta"
- [ ] potential edit / refine content of stage definitions
- [ ] talk to users of the dashboard and see if they get what is meant by those when they read our definition

**Comment by gboone** [comment]
Related to 18F/team_api#38

**Comment by melodykramer** [comment]
I'm going to assign myself to this.

**Comment by gboone** [comment]
We think there are two kinds of stages: 
1. Where the project is in our own process
2. How the team thinks about the status of their work in progress

There's a need for us to represent how much control over the product we have and where the work stands on the spectrum of our relationship with the partner agency. A product can be something we're working on (openFEC), something we aren't working on but plan to again (SBIR-EZ), or something we have transferred completely over to agencies (Peace Corps).

We _also_ think "alpha" and "beta" mean something to product owners when describing their products and we need to understand what they mean when they use those terms and what other terms they might use. Also, are there artifacts or specific milestones that happen before these labels can be applied or removed. How do product managers describe the qualitative status of their products? What, if any, terms can we use to meaningfully represent this on the dashboard?

Finally we need to think about how we represent both of these kinds of stages in the Dashboard.

**Comment by melodykramer** [comment]
I really like Greg's suggestion that we ask projects to check off whether they're:

being actively worked on | not being actively worked on | passed off to a partner agency.

But I'm stumbling a bit around the term beta, in part because I imagine not of our projects may really ever leave the beta stage. Would it be ok to have the term beta on a site and not have it reflected on the dashboard? Could it be on a page that is linked out from the dashboard?

Right now, we emphasize what stage a project is in above anything else. But is that something the user needs? Consider:
- someone who wants to learn more about products to contribute to an open source project
- someone interested in working for 18F
- someone at another agency wondering what products we’ve created and whether they should contact Intake
- someone in state/local government who wants to adopt our products
- the press, who may be interested in updates and nothing else.
- internal

These are all different use cases. I can imagine that knowing whether a project is active or not would be of interest, as well as how a team thinks about the status of their project. But I think the latter can be described in words and the former in the stages Greg suggested yesterday.

I really like the way Nick put it yesterday, when describing CALC. He said "We've never thought about alpha or beta because we're constantly iterating on the project." I think this is true for many of our projects, and having people pick a category might limit what we are able to say about the product itself.

**Comment by melodykramer** [comment]
I have the following questions out to the product leads:
- What do the terms alpha and beta mean to you?
-  Are there artifacts or specific milestones that happen before these labels can be applied or removed?
- How do you describe the qualitative status of your products? 
- What, if any, terms can we use to meaningfully represent this on the dashboard?
- Would you rather omit these terms entirely and describe your projects in a different way? If so, how?

**Comment by melodykramer** [comment]
Answers are here: https://docs.google.com/a/gsa.gov/document/d/12_D2OOqKmOompkgnWQBuMV9H6a9zvHmvhY5eNVVjO7s/edit?usp=sharing

**Comment by mtorres253** [comment]
I'm seeing a pattern at least. Beta means to people that the product is stable enough for public release and Alpha is a state where it's a real MVP, and we are just starting to gather user feedback

**Comment by melodykramer** [comment]
Greg's synopsis of research: https://docs.google.com/document/d/1fHnKVB5UBA3uVgqKogOt360sVpBZsjjpH1ltMKZDiEM/edit

**Comment by jeremiak** [comment]
We've completed the research portion of this task, so we've created an implementation task #320
